### ISSUE TITLE
Type parameter missing in save - please add to v3.9

### ISSUE THREAD

**Issue by melanietreitinger** [moodleuulm/moodle-availability_password#17]
This issue is still present in v3.9-r3 (actually every release but v3.11-r1). Would be cool if it could be fixed there as well.

As far as I can see, @christianwolters patch / pull request is applicable there as well.

Cheers

_Originally posted by @krostas1983 in https://github.com/moodle-an-hochschulen/moodle-availability_password/issues/11#issuecomment-1105199718_

**Comment by abias** [comment]
Hi @melanietreitinger ,

thank you for this hint. You are right, this patch should have been integrated into legacy branches as well. I have backported it now to 3.9 and 3.10 and will release new versions to moodle.org soon.

Cheers,
Alex
