### ISSUE TITLE
not working after upgrade to moodle 3.4.1

### ISSUE THREAD

**Issue by promedacademy** [moodleuulm/moodle-availability_password#4]
the module is not working after upgrade to moodle 3.4.1 and the option to restrict access to activity by password  does not show up in the selection list

**Comment by abias** [comment]
Hi promedacademy,

thank you for your issue report.

We haven't encountered this problem yet when we tested the plugin on Moodle 3.4. 

Could you please make sure:
* that you have enabled the availability plugin on /admin/tool/availabilityconditions/
* that the user you are trying to add the availability with has the availability/password:addinstance capability.

If both pitfalls are ok, could you please let me know:
* From which version (where availability_password was working for you) you upgraded to 3.4.1?
* If you are using the latest version of the plugin on 3.4.1?

Thanks,
Alex
