### ISSUE TITLE
Password Restriction

### ISSUE THREAD

**Issue by slydrone** [moodleuulm/moodle-availability_password#9]
Hi would it be possible for the restriction to work with tiles format perhaps extending the popup view time on mouse over. The problem is you can not click the password link in the popup when you mouse over the restriction label as it disappears.

Also could it work on restriction to a section 

Regards

Gordon

**Comment by abias** [comment]
Hi Gordon,

thank you for this request.

> Hi would it be possible for the restriction to work with tiles format perhaps extending the popup view time on mouse over. The problem is you can not click the password link in the popup when you mouse over the restriction label as it disappears.

As we are not using the tiles format here, I have to admit that I don't have an idea how this plugin would look like on the tiles format and what problems in could cause.

Could you please submit some screenshots or a screencast of the (mis)behaviour here?

> Also could it work on restriction to a section

A previous issue about protecting a whole section is #5 which was just closed as there wasn't any further need announced.

Protecting whole sections and the reasons why it currently does not work is explained in https://github.com/moodleuulm/moodle-availability_password#protection-course-sections.

My answer is the same as in #5: Currently, we don't have any local need and resources to implement this addition. But if anyone from the community will code it and submit a pull request in proper way, we can handle the pull request.

Cheers,
Alex

**Comment by slydrone** [comment]
Hi Alexandrer I have attached the screen shot of the password popup when used with tiles.


![image](https://user-images.githubusercontent.com/56204808/74632226-ca391f80-5156-11ea-82ab-75040baf2f91.png)

**Comment by abias** [comment]
Thank you for the screenshot.

I understand now that the tiles format seems to modify the availability information of an activity in a way that it does not show the full availability information below the activity but that it provides a popover with this information.

On the other hand, availability_password modifies the availability information in a way that it adds a clickable link to the availability information which is unique as far as I know.

We have a catch-22 now. Who is to blame for this situation - availability_password or the tiles format? I think there are arguments for both sides.

What I can say now:
* I do not think that we can include a fix for this situation into availability_password at the moment, as we strive to avoid including such fixes into our plugins for particular other plugins and as we don't use the tiles format here at the moment.
* availability_password does not only add a link to the availability information, it also makes the activity link itself clickable. If you click the activity link of a restricted activity, the password popup will open too. Please check if this still works for you or if this is also broken by the tiles format.

Cheers,
Alex

**Comment by slydrone** [comment]
Yes you can click it and it works. The only way I have found is to right click first which keeps the pop up open. 

Regards
Gordon Mills


> On 17 Feb 2020, at 13:49, Alexander Bias <notifications@github.com> wrote:
> 

﻿
Thank you for the screenshot.

I understand now that the tiles format seems to modify the availability information of an activity in a way that it does not show the full availability information below the activity but that it provides a popover with this information.

On the other hand, availability_password modifies the availability information in a way that it adds a clickable link to the availability information which is unique as far as I know.

We have a catch-22 now. Who is to blame for this situation - availability_password or the tiles format? I think there are arguments for both sides.

What I can say now:

I do not think that we can include a fix for this situation into availability_password at the moment, as we strive to avoid including such fixes into our plugins for particular other plugins and as we don't use the tiles format here at the moment.
availability_password does not only add a link to the availability information, it also makes the activity link itself clickable. If you click the activity link of a restricted activity, the password popup will open too. Please check if this still works for you or if this is also broken by the tiles format.
Cheers,
Alex

**Comment by abias** [comment]
> Yes you can click it and it works. The only way I have found is to right click first which keeps the pop up open.

Thanks for this feedback.

So, if your students can click on the activity title and it shows the password popup, the basic functionality of availability_password is working for you in my point of view.

How about adding some custom CSS to your theme then to change the color of the "you enter the correct password" link in the popup to match the color of the "Not available unless" text? 
This way, I would imagine, the link in the popover won't be received as a link anymore, students won't try to click it and won't fail. 
But when they click on the activity, they can still enter the password and access it.

**Comment by abias** [comment]
So I will close this issue now.
